version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik
    networks:
      - internal
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.frontend.rule=Host:traefik.${HOST_NAME}
      - traefik.port=8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - web
      - internal
    labels:
      - traefik.frontend.rule=Host:prometheus.${HOST_NAME}
      - traefik.frontend.auth.basic=admin:$$apr1$$19QaA1n1$$pSXbhasDra3x5.8IPm5UN/
      - traefik.port=9090

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - internal
    labels:
      - traefik.enable=false
      
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - traefik
      - prometheus
    labels:
      - traefik.backend=grafana
      - traefik.frontend.rule=Host:grafana.${HOST_NAME}
      - traefik.port=3000
    networks:
      - internal
      - web

volumes:
  grafana_data: {}
  prometheus_data: {}
