global:
    scrape_interval: 5s
    external_labels:
        monitor: 'default-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      scrape_interval: 10s
      static_configs:
          - targets: ['node-exporter:9100']
    - job_name: 'traefik'
      scrape_interval: 10s
      static_configs:
          - targets: ['traefik:8080']
rule_files:
  - 'alert.rules'
