version: '3'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.frontend.rule=Host:traefik.domain.com
      - traefik.port=8080